name: go-lint
on:
  pull_request:
    branches:
      - go-1.11
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest,ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          only-new-issues: true
